all:
	nasm -f elf -o loader.o asm/loader.asm
	gcc -m32 -o assembly.o -c asm/assembly.s -Wall -nostdlib -nostdinc -ffreestanding -nostartfiles -nodefaultlibs
	gcc -m32 -o multiboot-kernel.o -c src/multiboot-kernel.c -Wall -nostdlib -nostdinc -ffreestanding -nostartfiles -nodefaultlibs
	gcc -m32 -o video.o -c src/video.c -Wall -nostdlib -nostdinc -ffreestanding -nostartfiles -nodefaultlibs
	gcc -m32 -o string.o -c src/string.c -Wall -nostdlib -nostdinc -ffreestanding -nostartfiles -nodefaultlibs
	gcc -m32 -o printf.o -c src/printf.c -Wall -nostdlib -nostdinc -ffreestanding -nostartfiles -nodefaultlibs
	gcc -m32 -o interrupts.o -c src/interrupts.c -Wall -nostdlib -nostdinc -ffreestanding -nostartfiles -nodefaultlibs
	gcc -m32 -o errorhandler.o -c src/errorhandler.c -Wall -nostdlib -nostdinc -ffreestanding -nostartfiles -nodefaultlibs
	gcc -m32 -o keyboard.o -c src/keyboard.c -Wall -nostdlib -nostdinc -ffreestanding -nostartfiles -nodefaultlibs
	gcc -m32 -o timer.o -c src/timer.c -Wall -nostdlib -nostdinc -ffreestanding -nostartfiles -nodefaultlibs
	gcc -m32 -o kmalloc.o -c src/kmalloc.c -Wall -nostdlib -nostdinc -ffreestanding -nostartfiles -nodefaultlibs
	gcc -m32 -o paging.o -c src/paging.c -Wall -nostdlib -nostdinc -ffreestanding -nostartfiles -nodefaultlibs
	gcc -m32 -o ordered_array.o -c src/ordered_array.c -Wall -nostdlib -nostdinc -ffreestanding -nostartfiles -nodefaultlibs
	gcc -m32 -o ata.o -c src/ata.c -Wall -nostdlib -nostdinc -ffreestanding -nostartfiles -nodefaultlibs
	gcc -m32 -o iso9660.o -c src/iso9660.c -Wall -nostdlib -nostdinc -ffreestanding -nostartfiles -nodefaultlibs
	gcc -m32 -o debugger.o -c src/debugger.c -Wall -nostdlib -nostdinc -ffreestanding -nostartfiles -nodefaultlibs
	gcc -m32 -o memcpy.o -c src/memcpy.c -Wall -nostdlib -nostdinc -ffreestanding -nostartfiles -nodefaultlibs
	ld -m elf_i386_fbsd -T linker.ld -o kernel.bin loader.o multiboot-kernel.o video.o printf.o string.o interrupts.o assembly.o errorhandler.o keyboard.o timer.o kmalloc.o paging.o ordered_array.o ata.o iso9660.o debugger.o memcpy.o
	chmod ugo-x kernel.bin
	perl makeiso.pl

run: all
	qemu -cdrom sixty-four.iso
